/* AUTHOR: USMAN O. OLANREWAJU (BLU3-SKY) 
   MODIFY: 2026-04-22
*/ 

DROP TABLE IF EXISTS INSTRUCTOR;
DROP TABLE IF EXISTS EMPLOYEE; 
DROP TABLE IF EXISTS DEPARTMENT;
DROP VIEW  IF EXISTS TOP_INSTRUCTOR;
DROP VIEW IF  EXISTS TOP_EMPLOYEE;
.headers on
.mode column 
.mode table      

--Note: .mode table and other works depend on your sqlite version 
CREATE TABLE INSTRUCTOR(
	INST_ID                CHAR(5) PRIMARY KEY,
	INST_NAME           VARCHAR(20),
	DEPT_NAME                 VARCHAR(20),
	SALARY                    NUMERIC(6,2)
);

CREATE TABLE EMPLOYEE ( 
       EMP_ID INTEGER PRIMARY KEY, 

       DEPT_NAME   CHAR,

       SALARY NUMERIC (6,3), 
       EMP_NAME VARCHAR(20) 
); 

CREATE TABLE DEPARTMENT(  
	DEPT_NAME CHAR(20) PRIMARY KEY,
	DEPT_BUDGET NUMERIC (8,2), 
	DEPT_BLOCK  TEXT 
); 

INSERT INTO INSTRUCTOR VALUES ('A2012','John',  'CLOUD',350000.32),
			      ('A4321','Mark',  'FULL STACK',500000.32),
			      ('A2133','James',  'DEVOPs',700000.32);


INSERT INTO EMPLOYEE VALUES ('234129','CLOUD',700000.421,'USMAN'),
                            ('634129','FULL STACK',100000.420,'BEYZA'),
                            ('734129','DEVOPs',80000.021,'JOHN'),
                            ('834129','CLOUD',90000.001,'UFUK'),
                            ('534129','DEVOPs',110000.131,'LUKE'),
                            ('434129','CLOUD',60000.072,'ALICE'); 


INSERT INTO DEPARTMENT VALUES ('CLOUD',12000000.00,'D-BLOCK'),
                              ('FULL STACK',15000000.00,'C-BLOCK'),
			      ('DEVOPs',20000000.00,'M-BLOCK'); 



--Getting the combination of all TABLES  

SELECT * FROM DEPARTMENT  JOIN EMPLOYEE ON DEPARTMENT.DEPT_NAME=EMPLOYEE.DEPT_NAME JOIN INSTRUCTOR ON INSTRUCTOR.DEPT_NAME=EMPLOYEE.DEPT_NAME; 

-- CREATE A VIEW FOR TOP INSTRUCTOR

/* ((INSTRUCTOR JOIN DEPARTMENT ) SALARY > 350001)   ----> THIS IS RESISTRICTION(WHERE) 

{ DEPT_BUDGET,INSTRUCTOR SALARY,DEPT_NAME,INST_ID, INST_NAME} -----> PROJECTION(SELECT) 
 */ 

CREATE VIEW Top_Instructor AS SELECT DEPARTMENT.DEPT_BUDGET, INSTRUCTOR.SALARY, INSTRUCTOR.DEPT_NAME, INSTRUCTOR.INST_ID, INSTRUCTOR.inst_name FROM INSTRUCTOR JOIN DEPARTMENT ON INSTRUCTOR.DEPT_NAME=DEPARTMENT .DEPT_NAME WHERE INSTRUCTOR.SALARY > 350001; 

SELECT * FROM TOP_INSTRUCTOR; 

-- CREATE A VIEW FOR TOP EMPLOYEE

CREATE VIEW TOP_EMPLOYEE AS SELECT EMPLOYEE.EMP_NAME, EMPLOYEE.EMP_ID, EMPLOYEE.SALARY,DEPARTMENT.DEPT_BUDGET,DEPARTMENT.DEPT_BLOCK FROM EMPLOYEE JOIN DEPARTMENT ON  EMPLOYEE.DEPT_NAME=DEPARTMENT.DEPT_NAME WHERE EMPLOYEE.SALARY > 80000 ;

SELECT * FROM TOP_EMPLOYEE; 
